# Master-script Data extraction and merging
## NB: If hBayesDM-data does not exist, it will run these too! Depending on your system this will take 12hours!
source("Loading-files.R")
source("Data-extraction-ART.R")
source("Data-extraction-BeadsOnejarTask.R")
source("Data-extraction-BeadsToneTask.R")
source("Data-extraction-BeadsTwojarTask.R")
source("Data-extraction-BoxIrregTask.R")
source("Data-extraction-BoxNormTaskLog.R")
source("Data-extraction-BoxNormTaskXlsx.R")
source("Data-extraction-Cape.R")
source("hBayesDM-ART.R")
source("Data-merging.R")
source("Sequences.R")
source("Demographics.R")
source("Ideal Baysian Observer.R")
source("IBO-FreeSequenceBox.R")
write.csv(All, file = paste(getwd(), "/Cleaned data/AllData.csv", sep =""))